### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hakxcore** [useless-tools/pixelate#1]
even i have installed both setuptools and pixelate

$ python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

$ cd bin && ./pixelate --input=/img/bps.jpg --output=/img/test.png --pixel-size=10
Traceback (most recent call last):
  File "./pixelate", line 4, in <module>
    from pixelate.pixelate import pixelate
ImportError: No module named pixelate.pixelate

**Comment by bugov** [comment]
Please use `pip3 install pixelate` to install the package. After this you can use pixelate as the installed program. Like this: `pixelate --input=path/to/input.jpg --output=path/to/output.png --pixel-size=10`
